#!/bin/bash

# Delete dummy VIM if registered
osm vim-show dummy_vim > /dev/null 2>&1 && ( echo "-- Deleting dummy_vim..."; osm vim-delete --wait dummy_vim )

osm vim-create --name dummy_vim --user u --password p --tenant p \
--account_type dummy --auth_url http://localhost/dummy --wait

osm vim-list

# Delete microk8s-cluster registration if already registered
osm k8scluster-show microk8s-cluster > /dev/null 2>&1 && ( echo "-- Deleting microk8s-cluster previous registration..."; osm k8scluster-delete --wait microk8s-cluster )
sleep 6

#read -p "PAK"

echo "-- Creating config yaml"
microk8s.config > k8s-cluster.yaml

echo "-- Registering microk8s-cluster"
KID=$(osm k8scluster-add --creds k8s-cluster.yaml --version 1.31 --vim dummy_vim --description "External k8s cluster" --k8s-nets '{"net1": "osm-ext"}' microk8s-cluster)

osm k8scluster-list

#read -p "PAK"
#osm k8scluster-show --literal $KID | grep -A1 projects
OSMNS=$( osm k8scluster-show --literal $KID | awk '/projects_read/{getline;print $2}' )
export OSMNS
echo "-- KID=$KID"
echo "-- OSMNS=$OSMNS"

sed -i -e '/OSMNS/d' ~/.bashrc
echo "export OSMNS=$OSMNS" >> ~/.bashrc

# Create OSM namespace if not already created
echo "-- kubectl get namespace $OSMNS"
microk8s kubectl get namespace $OSMNS >/dev/null 2>&1 || microk8s kubectl create namespace $OSMNS 
microk8s kubectl get namespace $OSMNS

# Enable access to services running on the host machine via fixed IP address
microk8s enable host-access

# Enable NGINX Ingress Controller for MicroK8 to access pod services through localhost:port
microk8s enable ingress


# Create external interfaces
echo "Creating external interfaces"
sudo ovs-vsctl --if-exists del-br AccessNet1
sudo ovs-vsctl --if-exists del-br AccessNet2
sudo ovs-vsctl --if-exists  del-br ExtNet1
sudo ovs-vsctl --if-exists  del-br ExtNet2
sudo ovs-vsctl --if-exists  del-br MplsWan
sudo ovs-vsctl add-br AccessNet1
sudo ovs-vsctl add-br AccessNet2
sudo ovs-vsctl add-br ExtNet1
sudo ovs-vsctl add-br ExtNet2
sudo ovs-vsctl add-br MplsWan

# Configure Multus accessnet1
microk8s kubectl get -n $OSMNS network-attachment-definitions accessnet1 || \
cat <<EOF | microk8s kubectl create -n $OSMNS -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: accessnet1
 annotations:
   k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/AccessNet1
spec:
 config: '{
   "cniVersion": "0.3.1",
   "type": "ovs",
   "bridge": "AccessNet1"
 }'
EOF

# Configure Multus accessnet2
microk8s kubectl get -n $OSMNS network-attachment-definitions accessnet2 || \
cat <<EOF | microk8s kubectl create -n $OSMNS -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: accessnet2
 annotations:
   k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/AccessNet2
spec:
 config: '{
   "cniVersion": "0.3.1",
   "type": "ovs",
   "bridge": "AccessNet2"
 }'
EOF

# Configure Multus extnet1
microk8s kubectl get -n $OSMNS network-attachment-definitions extnet1 || \
cat <<EOF | microk8s kubectl create -n $OSMNS -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: extnet1
 annotations:
   k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/ExtNet1
spec:
 config: '{
   "cniVersion": "0.3.1",
   "type": "ovs",
   "bridge": "ExtNet1"
 }'
EOF


# Configure Multus extnet2
microk8s kubectl get -n $OSMNS network-attachment-definitions extnet2 || \
cat <<EOF | microk8s kubectl create -n $OSMNS -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: extnet2
 annotations:
   k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/ExtNet2
spec:
 config: '{
   "cniVersion": "0.3.1",
   "type": "ovs",
   "bridge": "ExtNet2"
 }'
EOF


# Configure Multus mplswan
microk8s kubectl get -n $OSMNS network-attachment-definitions mplswan || \
cat <<EOF | microk8s kubectl create -n $OSMNS -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: mplswan
 annotations:
   k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/MplsWan
spec:
 config: '{
   "cniVersion": "0.3.1",
   "type": "ovs",
   "bridge": "MplsWan"
 }'
EOF

echo "-- kubectl get -n $OSMNS network-attachment-definitions"
microk8s kubectl get -n $OSMNS network-attachment-definitions
