#!/bin/bash

# Delete dummy VIM if registered
osm vim-show dummy_vim > /dev/null 2>&1 && ( echo "-- Deleting dummy_vim..."; osm vim-delete --wait dummy_vim )

osm vim-create --name dummy_vim --user u --password p --tenant p --account_type dummy --auth_url http://localhost/dummy --wait

osm vim-list

# Delete microk8s-cluster registration if already registered
osm k8scluster-show microk8s-cluster > /dev/null 2>&1 && (echo "-- Deleting microk8s-cluster previous registration..."; osm k8scluster-delete --wait microk8s-cluster)
sleep 6

#read -p "PAK"

echo "-- Creating config yaml"
microk8s.config > k8s-cluster.yaml

echo "-- Registering microk8s-cluster"
KID=$(osm k8scluster-add --creds k8s-cluster.yaml --version 1.31 --vim dummy_vim --description "External k8s cluster" --k8s-nets '{"net1": "osm-ext"}' --skip-jujubundle --wait microk8s-cluster)

echo "export KID=$KID" >> ~/.bashrc

osm k8scluster-list

echo "----------------------------------------------------------------------------------------------"
echo "If you didn't run this command with source, you need to run \"source ~/.bashrc\" or close this terminal and open another for the variables to be updated."
echo "----------------------------------------------------------------------------------------------"
