#!/bin/bash

OVAFILE_OSM='RDSV-OSM-2026.ova'
OVAFILE_K8S='RDSV-K8S-2024-v2.ova'
LABDIR=/lab/rdsv/repo
VMNAME_OSM='RDSV-OSM-2026'
VMNAME_K8S='RDSV-K8S-2024-v2'
NATNETWORK='Nat_OSM'

START_TIME=$SECONDS

check_in_vbox(){
if vboxmanage list vms | grep $1; then
    echo "--"
    echo "-- ERROR: $VMNAME virtual machine alredy exists in VirtualBox."
    echo "--        Delete or rename it manually and execute this script again."
    echo "--"
    exit 1
fi
}

cd /mnt/tmp/
#wget http://idefix.dit.upm.es/download/vnx/vnx-vm/$OVAFILE
#rsync --progress /lab/rdsv/$OVAFILE .

#ELAPSED_TIME=$(($SECONDS - $START_TIME))
#echo "--"
#echo "-- File copied in: $ELAPSED_TIME sec"
#echo "--"

check_in_vbox $VMNAME_OSM
check_in_vbox $VMNAME_K8S

echo "--"
echo "-- Creating NAT Network..."
echo "--"
VBoxManage natnetwork add --netname="$NATNETWORK" --network="10.0.2.0/24" --enable

# Enable dhcp in case it's not.
VBoxManage natnetwork modify --netname $NATNETWORK --dhcp on

# If hostonlynet is used, disable the NAT network part.

#if ! vboxmanage list hostonlyifs | grep -q vboxnet0 ; then
#    echo "Creating vboxnet0 as it doesn't already exist."
#    vboxmanage hostonlyif create 
#fi
#echo "--"
#echo "-- Configuring vboxnet0..."
#echo "-- IP: 192.168.56.1"
#echo "-- Netmask: 255.255.255.0"
#echo "--"
#vboxmanage hostonlyif ipconfig vboxnet0 --ip=192.168.56.1 --netmask=255.255.255.0

echo "--"
echo "-- Creating temporary VirtualBox folder for $USER..."
echo "--"
mkdir -p /mnt/tmp/cache/$USER/VirtualBox/
vboxmanage setproperty machinefolder /mnt/tmp/cache/$USER/VirtualBox/

echo "--"
echo "-- Importing $OVAFILE_OSM into VirtualBox..."
echo "--"
echo vboxmanage import /$LABDIR/$OVAFILE_OSM
vboxmanage import $LABDIR/$OVAFILE_OSM

echo "--"
echo "-- Importing $OVAFILE_K8S into VirtualBox..."
echo "--"
echo vboxmanage import /$LABDIR/$OVAFILE_K8S
vboxmanage import $LABDIR/$OVAFILE_K8S

echo "--"
echo "-- Creating Shared folder for K8S VM..."
echo "--"
mkdir -p ~/shared
#vboxmanage sharedfolder add $VMNAME_OSM --name shared --hostpath ~/shared --automount --auto-mount-point=/home/upm/shared
vboxmanage sharedfolder add $VMNAME_K8S --name shared --hostpath ~/shared --automount --auto-mount-point=/home/upm/shared

echo "--"
echo "-- Connecting $VMNAME_OSM to NAT Network \"$NATNETWORK\"..."
echo "--"
VBoxManage modifyvm $VMNAME_OSM --nic1 natnetwork --natnet1 $NATNETWORK

echo "--"
echo "-- Connecting $VMNAME_K8S to NAT Network \"$NATNETWORK\"..."
echo "--"
VBoxManage modifyvm $VMNAME_K8S --nic1 natnetwork --natnet1 $NATNETWORK

# Force the Nat Network to run in case it doesn't automatically.
VBoxManage natnetwork start --netname $NATNETWORK

# If hostonlynet is used, disable the NAT network part.

#echo "--"
#echo "-- Setting network adapter for $VMNAME_OSM to host only adapter vboxnet0..."
#echo "--"
# Set Adapter 1 to Host-only mode
#vboxmanage modifyvm "$VMNAME_OSM" --nic1 hostonly

# Bind Adapter 1 to the vboxnet0 interface
#vboxmanage modifyvm "$VMNAME_OSM" --hostonlyadapter1 vboxnet0

#echo "--"
#echo "-- Setting network adapter for $VMNAME_K8S to host only adapter vboxnet0..."
#echo "--"
# Set Adapter 1 to Host-only mode
#vboxmanage modifyvm "$VMNAME_K8S" --nic1 hostonly

# Bind Adapter 1 to the vboxnet0 interface
#vboxmanage modifyvm "$VMNAME_K8S" --hostonlyadapter1 vboxnet0

# If you need to reduce RAM for OSM machine, 12 GiB should be enough for small scenarios. Less than that probably will not run.
#vboxmanage modifyvm $VMNAME_OSM --memory 12288

ELAPSED_TIME=$(($SECONDS - $START_TIME))
echo "--"
echo "-- Total command duration: $ELAPSED_TIME sec"
echo "--"

echo "--"
echo "-- You can run \"watch kubectl get pods -n osm\" on the OSM VM to check if OSM is done loading."
echo "--"
